### ISSUE TITLE
Unable to run as service

### ISSUE THREAD

**Issue by msageryd** [mlsorensen/apollo#9]
I'm now up and running with Apollo. It works fine when I start apollo.py in the shell. But I'm unable to run it as a service.

`sudo systemctl status apollo.service` 
Gives the following.
I suspect that I need to move fonts somewhere, or maybe define a working directory. I'll tinker some more, but I thought maybe you  could spot the problem?

```
Apr 07 19:22:43 lineamicra systemd[1]: Started Apollo service - Acaia Lunar add-on.
Apr 07 19:22:45 lineamicra python3[1327]: Traceback (most recent call last):
Apr 07 19:22:45 lineamicra python3[1327]:   File "/opt/apollo/apollo.py", line 16, in <module>
Apr 07 19:22:45 lineamicra python3[1327]:     from lib.display import Display, DisplayData, DisplaySize
Apr 07 19:22:45 lineamicra python3[1327]:   File "/opt/apollo/lib/display.py", line 15, in <module>
Apr 07 19:22:45 lineamicra python3[1327]:     label_font = ImageFont.truetype("lib/font/LiberationMono-Regular.ttf", 16)
Apr 07 19:22:45 lineamicra python3[1327]:   File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 852, in truetype
Apr 07 19:22:45 lineamicra python3[1327]:     return freetype(font)
Apr 07 19:22:45 lineamicra python3[1327]:   File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 849, in freetype
Apr 07 19:22:45 lineamicra python3[1327]:     return FreeTypeFont(font, size, index, encoding, layout_engine)
Apr 07 19:22:45 lineamicra python3[1327]:   File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 209, in __init__
Apr 07 19:22:45 lineamicra python3[1327]:     self.font = core.getfont(
Apr 07 19:22:45 lineamicra python3[1327]: OSError: cannot open resource

**Comment by msageryd** [comment]
Never mind. I found the solution.

Added the following under [Service] in apollo.service:
`WorkingDirectory=/opt/apollo`
